export type ProjectBase = {
  slug: string;
  title: string;
  category: string;
  location: string;
  summary: string;
  description: string;
  role: string;
  services: string[];
  metrics: { label: string; value: string }[];
  folder: string;
  heroImage: string;
  projectNumber?: string;
  assignmentName?: string;
  contractValue?: string;
  country?: string;
  duration?: string;
  procuringEntity?: string;
  staffMonths?: string;
  address?: string;
  startDate?: string;
  completionDate?: string;
  associatedConsultants?: string;
  roleOnAssignment?: string;
  seniorProfessionalStaff?: string[];
  responsibilities?: string[];
  narrativeDescription?: string;
  actualServicesProvided?: string[];
  consultingFirm?: string;
  signatory?: string;
};

export const projects: ProjectBase[] = [
  {
    slug: "lumumba-affordable-housing",
    title: "Lumumba Affordable Housing",
    category: "Affordable Housing",
    location: "Kisumu County",
    summary: "Large-scale affordable housing and social infrastructure project designed to deliver a high-impact urban residential programme with strong cost control and project management oversight.",
    description:
      "KEMSAL supported the design and implementation of a major affordable housing development through project management, quantity surveying, architectural coordination, and engineering oversight. The assignment focused on keeping the programme aligned to budget, schedule, and quality while supporting the client on delivery of social infrastructure and residential units.",
    role: "Project management and quantity surveying leadership for detailed cost planning, procurement support, contract administration, and financial reporting throughout the project lifecycle.",
    services: ["Project management", "Cost planning", "Tendering & procurement", "Contract administration", "Cost control"],
    metrics: [
      { label: "Units", value: "2,348" },
      { label: "Value", value: "Ksh. 5.75B" },
      { label: "Status", value: "Ongoing" },
    ],
    folder: "lumumba-affordable-housing",
    heroImage: "/projects/lumumba-affordable-housing/Project-1-Image-5.jpeg",
    projectNumber: "Project No. 1",
    assignmentName: "Proposed construction of Lumumba Affordable Housing and associated social infrastructure at Kisumu central constituency, Kisumu county",
    contractValue: "Ksh. 5.75 billion",
    country: "Kenya",
    duration: "18 months",
    procuringEntity: "Ministry of Lands, Public Works, Housing and Urban Development",
    staffMonths: "18 months",
    address: "Ardhi House, 1st Ngong Road Avenue, P.O. Box 30119-00100, Nairobi",
    startDate: "June 2024",
    completionDate: "Ongoing",
    associatedConsultants: "N/A",
    roleOnAssignment: "Provision of Project Management, Architectural, Quantity Surveying, Structural Engineering, Mechanical and Electrical Engineering services",
    seniorProfessionalStaff: ["Qs. Olivia S. Otieno"],
    responsibilities: [
      "Project Manager on this assignment",
      "Responsible for quality assurance and control for all deliverables",
      "Developing the detailed project plan for discussion and agreement with SDHUD",
      "Preparing detailed work plans, survey tools, and project report structures",
      "Preparing draft and final reports",
      "Liaison with the client",
    ],
    narrativeDescription:
      "The main objective of the consultancy is to offer the optimal technical advice and project management towards the design and construction of affordable houses for SDHUD. The proposed development comprises 14 blocks of G + 16 apartment blocks plus 1 block G + 11 mixed-use development block, totalling 2,348 units, along with social infrastructure and related amenities. The gross development area is 144,482m2.",
    actualServicesProvided: [
      "Provision of Project Management",
      "Architectural services",
      "Quantity Surveying services",
      "Structural Engineering services",
      "Mechanical Engineering services",
      "Electrical Engineering services",
    ],
    consultingFirm: "Kemsal Consultants Ltd",
    signatory: "Qs. Olivia. S. Otieno – Director",
  },
  {
    slug: "advent-towers-riverside",
    title: "Advent Towers Residential Suites",
    category: "Residential",
    location: "Riverside Drive, Nairobi",
    summary: "Luxury residential tower development requiring cost control, tender documentation, and construction project management support.",
    description:
      "KEMSAL provided quantity surveying and cost advice for the design and supervision of a multi-storey residential development. The role focused on feasibility support, tender documentation, and construction project management across the project lifecycle.",
    role: "Quantity surveying and project management support covering feasibility studies, tender documentation, contract administration, and construction oversight.",
    services: ["Feasibility studies", "Tender documentation", "Construction project management", "Contract administration"],
    metrics: [
      { label: "Value", value: "Ksh. 1.2B" },
      { label: "Duration", value: "Ongoing" },
      { label: "Partner", value: "Otieno & Kungu" },
    ],
    folder: "advent-towers-riverside",
    heroImage: "/projects/advent-towers-riverside/Project-2-Image-1.jpeg",
    projectNumber: "Project No. 2",
    assignmentName: "Proposed Advent Towers, Residential Suites on Plot LR No. 209/7574, Riverside – Riverside Drive, Nairobi County",
    contractValue: "Kshs. 1.2 billion",
    country: "Kenya",
    duration: "Ongoing",
    procuringEntity: "The General Conference Co-operation of Seventh Day Adventist (SDA) Limited",
    staffMonths: "Ongoing",
    address: "The General Conference, Riverside, P.O. Box 14756-00511, Nairobi",
    startDate: "January 2022",
    completionDate: "Ongoing",
    associatedConsultants: "24 months in association with Otieno & Kungu Associates",
    roleOnAssignment: "Provision of Project Management, Architectural, Quantity Surveying, Structural Engineering, Mechanical and Electrical Engineering services",
    seniorProfessionalStaff: ["Qs. Olivia S. Otieno"],
    responsibilities: [
      "Tender documentation",
      "Feasibility studies",
      "Construction project management",
      "Contract administration",
    ],
    narrativeDescription:
      "Kemsal Consultants Limited’s role is to provide quantity surveying and cost advice services towards the design and supervision of the 10-storey building (Block A and Block B) consisting of high-end 1-bedroom and 2-bedroom apartments. The main objective is to offer optimal technical and cost-effective solutions for postgraduate student accommodation. The proposed development provides two blocks up to completion of 2 basements, upper ground floor, mezzanine floors, and 8 typical floor apartments.",
    actualServicesProvided: [
      "Provision of Project Management",
      "Architectural services",
      "Quantity Surveying services",
      "Structural Engineering services",
      "Mechanical Engineering services",
      "Electrical Engineering services",
    ],
    consultingFirm: "Kemsal Consultants Ltd",
    signatory: "Qs. Olivia. S. Otieno – Director",
  },
  {
    slug: "upper-kanyakwar-affordable-housing",
    title: "Upper Kanyakwar Affordable Housing",
    category: "Affordable Housing",
    location: "Kisumu East, Kisumu County",
    summary: "Affordable housing project focused on delivering mixed residential and social infrastructure with coordinated project control and cost management.",
    description:
      "KEMSAL supported the project by providing project management, quantity surveying, and engineering coordination from concept to delivery. The project required strong cost discipline and a clear programme for multi-block construction and associated amenities.",
    role: "Quantity surveying and project management support covering design coordination, cost control, planning, procurement, and contractor oversight.",
    services: ["Cost planning", "Project management", "Tendering", "Contract administration", "Technical coordination"],
    metrics: [
      { label: "Value", value: "Ksh. 1.73B" },
      { label: "Units", value: "1,000" },
      { label: "Duration", value: "24 months" },
    ],
    folder: "upper-kanyakwar-affordable-housing",
    heroImage: "/projects/upper-kanyakwar-affordable-housing/Project-3-Image-1.jpeg",
    projectNumber: "Project No. 3",
    assignmentName: "Proposed construction of Upper Kanyakwar Affordable Housing and associated social infrastructure at Kisumu East constituency, Kisumu county",
    contractValue: "Ksh. 1.73 billion",
    country: "Kenya",
    duration: "24 months",
    procuringEntity: "Ministry of Lands, Public Works, Housing and Urban Development",
    staffMonths: "24 months",
    address: "Ardhi House, 1st Ngong Road Avenue, P.O. Box 30119-00100, Nairobi",
    startDate: "June 2025",
    completionDate: "Ongoing",
    associatedConsultants: "N/A",
    roleOnAssignment: "Provision of Project Management, Architectural, Quantity Surveying, Structural Engineering, Mechanical and Electrical Engineering services",
    seniorProfessionalStaff: ["Qs. Olivia S. Otieno"],
    responsibilities: [
      "Project Manager on this assignment",
      "Responsible for quality assurance and control for all deliverables",
      "Preparing detailed project plan and reports",
      "Liaison with the client",
    ],
    narrativeDescription:
      "The main objective of the consultancy is to offer optimal technical advice and project management towards the construction of affordable houses for SDHUD. The proposed development includes five blocks of G + 9 apartment blocks and one block G + 14 mixed-use development block, totalling 1,000 units, supported by social infrastructure and related amenities. The gross development area is 50,000m2.",
    actualServicesProvided: [
      "Provision of Project Management",
      "Architectural services",
      "Quantity Surveying services",
      "Structural Engineering services",
      "Mechanical Engineering services",
      "Electrical Engineering services",
    ],
    consultingFirm: "Kemsal Consultants Ltd",
    signatory: "Qs. Olivia. S. Otieno – Director",
  },
  {
    slug: "fawe-head-office",
    title: "FAWE Head Office Facility",
    category: "Institutional",
    location: "Nairobi",
    summary: "Three-floor institutional office development requiring structured design progression, procurement support, and construction supervision.",
    description:
      "The assignment centred on delivering a modern office facility for the Forum for African Women Educationalists (FAWE), with an emphasis on effective design management and site supervision. KEMSAL supported the client in maintaining quality, budget discipline, and timely implementation.",
    role: "Project management, architectural, and quantity surveying support for the design and construction phases of the office block.",
    services: ["Project management", "Design coordination", "Tendering", "Construction supervision", "Contract administration"],
    metrics: [
      { label: "Value", value: "Ksh. 40M" },
      { label: "Duration", value: "6 months" },
      { label: "Status", value: "Completed" },
    ],
    folder: "kehancha-estate",
    heroImage: "/projects/kehancha-estate/image_3.jpeg",
    projectNumber: "Project No. 4",
    assignmentName: "The Design & Construction of a Three - Floor Office Block Located at FAWE Head Office Facility at Chania Avenue, off Wood Avenue Kilimani, Ngong Road, Nairobi, Kenya",
    contractValue: "40M",
    country: "Kenya",
    duration: "6 months",
    procuringEntity: "Forum for African Women Educationalists (FAWE)",
    staffMonths: "6 months",
    address: "FAWE Head Office, P.O. Box 52597 – 00200, Nairobi",
    startDate: "January 2022",
    completionDate: "February 2023",
    associatedConsultants: "N/A",
    roleOnAssignment: "Provision of Project Management, Architectural, Quantity Surveying, Structural Engineering, Mechanical and Electrical Engineering services",
    seniorProfessionalStaff: ["Qs. Olivia S. Otieno"],
    responsibilities: [
      "Project Manager on this assignment",
      "Quality assurance and control of all deliverables",
      "Detailed project planning and meeting coordination",
      "Preparation of project reports",
      "Client liaison",
    ],
    narrativeDescription:
      "The main objective of the consultancy is to offer optimal technical advice and project management towards the design and construction of a three-floor office block for FAWE. The proposed development provides a basement, ground floor, typical first and second floor, and a terrace floor.",
    actualServicesProvided: [
      "Provision of Project Management",
      "Architectural services",
      "Quantity Surveying services",
      "Structural Engineering services",
      "Mechanical Engineering services",
      "Electrical Engineering services",
    ],
    consultingFirm: "Kemsal Consultants Ltd",
    signatory: "Qs. Olivia. S. Otieno – Director",
  },
  {
    slug: "kra-rapid-response-units",
    title: "KRA Rapid Response Units",
    category: "Institutional",
    location: "Northern Kenya and Customs Routes",
    summary: "Design, refurbishment, bidding documentation, and supervision of customs infrastructure and rapid response units across strategic trade corridors.",
    description:
      "KEMSAL supported the Kenya Revenue Authority in improving customs infrastructure and operational readiness by preparing designs, overseeing refurbishment works, and providing supervision support for the delivery of rapid response units and customs station upgrades. The project aligned to Kenya Vision 2030 revenue collection and trade security objectives.",
    role: "Technical design review, supervision, procurement support, and project monitoring for customs and infrastructure works.",
    services: ["Design support", "Refurbishment planning", "Bidding documentation", "Supervision", "Project monitoring"],
    metrics: [
      { label: "Value", value: "Approx. Ksh. 550M" },
      { label: "Duration", value: "12 months" },
      { label: "Site count", value: "4 RRU units" },
    ],
    folder: "kra-rapid-response-units",
    heroImage: "/projects/kra-rapid-response-units/Project-5-Image-1.png",
    projectNumber: "Project No. 5",
    assignmentName: "Design of KRA Rapid Response Units (RRU) & refurbishment of Nadapal Customs Station and preparation of bidding documents and supervision of works",
    contractValue: "Approx. 550M",
    country: "Kenya",
    duration: "12 months",
    procuringEntity: "Kenya Revenue Authority",
    staffMonths: "12 months",
    address: "P.O. Box 48240 – 00100, Nairobi",
    startDate: "N/A",
    completionDate: "N/A",
    associatedConsultants: "N/A",
    roleOnAssignment: "Ensuring quality assurance, project supervision, independent review, dispute resolution support, and project monitoring",
    seniorProfessionalStaff: ["Qs. Olivia S. Otieno"],
    responsibilities: [
      "Ensuring high standards of quality assurance in execution of works",
      "Undertaking supervision of project implementation activities",
      "Reviewing design and construction compliance with contract requirements",
      "Assisting in amicable settlement of disputes",
      "Providing project management and monitoring support",
    ],
    narrativeDescription:
      "The construction of four rapid response units and refurbishment of Nadapal Customs Office is intended to mitigate challenges in revenue collection and improve customs monitoring capacity along key trade corridors. The project falls within the national objective of strengthening Kenya’s ability to account for and secure trade-related revenues under Vision 2030.",
    actualServicesProvided: [
      "Pre-contract design planning and detailed design layouts",
      "Structural and civil engineering input",
      "Quantity surveying",
      "Mechanical and electrical engineering information",
      "Environmental and social impact assessment support",
      "Preparation of bid documents",
      "Full-time post-contract supervision",
    ],
    consultingFirm: "Kemsal Consultants Ltd",
    signatory: "Qs. Olivia. S. Otieno – Director",
  },
  {
    slug: "kra-staff-housing-shimoni",
    title: "KRA Staff Housing, Shimoni",
    category: "Residential",
    location: "Shimoni, Kwale County",
    summary: "Cost-effective staff housing design and supervision using efficient building technology and disciplined project delivery.",
    description:
      "This project involved design, documentation, and supervision for a staff housing development in Shimoni. KEMSAL contributed to the preparation of project documentation and monitoring of works, with a focus on delivering affordable, efficient residential units using innovative construction methods.",
    role: "Design documentation and construction supervision support for staff housing works.",
    services: ["Bills of quantities", "Tender documentation", "Construction management", "Contract administration"],
    metrics: [
      { label: "Units", value: "26" },
      { label: "Duration", value: "6 months" },
      { label: "Value", value: "Ksh. 83.5M" },
    ],
    folder: "kra-staff-housing-shimoni",
    heroImage: "/projects/kra-staff-housing-shimoni/Project-6-Image-1.jpeg",
    projectNumber: "Project No. 6",
    assignmentName: "Design, documentation and construction supervision of proposed KRA staff housing development in Shimoni, Kwale County",
    contractValue: "Kshs. 83,500,000",
    country: "Kenya",
    duration: "6 months",
    procuringEntity: "Kenya Revenue Authority",
    staffMonths: "8 staff",
    address: "Times Tower Building, P.O. Box 48240 – 00100, Nairobi",
    startDate: "July 2017",
    completionDate: "June 2018",
    associatedConsultants: "University of Nairobi, Department of Architecture and Building Sciences",
    roleOnAssignment: "Design, documentation and construction supervision",
    seniorProfessionalStaff: ["Prof Madara Ogot"],
    responsibilities: [
      "Team leader on this assignment",
      "Quality assurance and control for all deliverables",
      "Developing detailed architectural plans",
      "Leading meetings and presentations",
    ],
    narrativeDescription:
      "The main objective of the consultancy is to offer optimal technical and cost-effective solutions towards the design and implementation of KRA staff housing. The proposed development provides 10 no. 2-bedroom and 16 no. 1-bedroom units in phase one. The units will be built using Expanded Polystyrene (EPS) technology to achieve cost-effective solutions within the least time.",
    actualServicesProvided: [
      "Preparation of Bills of Quantities",
      "Tender documentation",
      "Construction management",
      "Contract administration",
    ],
    consultingFirm: "Kemsal Consultants Ltd",
    signatory: "Qs. Olivia. S. Otieno – Director",
  },
  {
    slug: "huduma-centres-refurbishment",
    title: "Huduma Centres Refurbishment",
    category: "Institutional",
    location: "Nairobi",
    summary: "Design and supervision of multiple Huduma Centre refurbishment works across Kenya’s service delivery hubs.",
    description:
      "The project involved design and supervision of Huduma Centre upgrades in multiple locations, focusing on improving customer-facing facilities and public service delivery environments.",
    role: "Design and supervision support for refurbishment works across service centre facilities.",
    services: ["Design supervision", "Refurbishment works", "Project administration"],
    metrics: [
      { label: "Centres", value: "11" },
      { label: "Value", value: "Ksh. 30M" },
      { label: "Duration", value: "2 months" },
    ],
    folder: "huduma-centres-refurbishment",
    heroImage: "/projects/huduma-centres-refurbishment/Project-7-Image-1.jpeg",
    projectNumber: "Project No. 7",
    assignmentName: "Design and Supervision – Huduma Centres",
    contractValue: "Kshs. 30,000,000.00",
    country: "Kenya",
    duration: "2 months",
    procuringEntity: "Ministry of Devolution and Planning",
    staffMonths: "6 staff",
    address: "Nairobi",
    startDate: "September 2013",
    completionDate: "October 2013",
    associatedConsultants: "University of Nairobi and Ministry of Housing, Land and Urban Development",
    roleOnAssignment: "Design and supervision",
    seniorProfessionalStaff: ["Arch. Kigara Kamweru", "Qs. Olivia Sally"],
    responsibilities: ["Project design and supervision", "Administrative support", "Contract coordination"],
    narrativeDescription: "Design and supervision of refurbishment works for Huduma Centres across multiple regions to improve facility usability and public service delivery.",
    actualServicesProvided: ["Design and supervision", "Administrative coordination", "Project oversight"],
    consultingFirm: "Kemsal Consultants Ltd",
    signatory: "Qs. Olivia. S. Otieno – Director",
  },
  {
    slug: "eldoret-eco-industrial-park",
    title: "Eldoret Eco Industrial Park",
    category: "Commercial",
    location: "Eldoret Municipality",
    summary: "Master planning and documentation for a strategic industrial and commercial park supporting SME growth and industrial development.",
    description:
      "KEMSAL supported the design and documentation of an industrial park that would serve as a modern industrial and commercial hub. The assignment involved concept development, planning, and a strategic approach tailored to Kenya’s Vision 2030 manufacturing agenda.",
    role: "Quantity surveying and project planning support for industrial park design and documentation.",
    services: ["Master planning", "Cost estimation", "Design documentation", "Project planning"],
    metrics: [
      { label: "Land size", value: "135 acres" },
      { label: "Value", value: "Ksh. 86M" },
      { label: "Duration", value: "8 months" },
    ],
    folder: "eldoret-eco-industrial-park",
    heroImage: "/projects/eldoret-eco-industrial-park/Project-8-Image-1.png",
    projectNumber: "Project No. 8",
    assignmentName: "Design and documentation of the Eldoret industrial park on Eldoret municipality block 15/1757",
    contractValue: "Kshs. 86,000,000",
    country: "Kenya",
    duration: "8 months",
    procuringEntity: "Industrial and Commercial Development Corporation (ICDC)",
    staffMonths: "2 staff",
    address: "Uchumi House, Aga Khan Walk, P.O. Box 45519-00100, Nairobi",
    startDate: "June 2015",
    completionDate: "2017",
    associatedConsultants: "University of Nairobi and associated specialists",
    roleOnAssignment: "Master planning and design documentation",
    seniorProfessionalStaff: ["Prof Peter Ngau"],
    responsibilities: [
      "Team leader on this assignment",
      "Quality assurance and control",
      "Project planning and reporting",
      "Client liaison",
    ],
    narrativeDescription:
      "As stipulated in the terms of reference, the main objective of the consultancy is to offer optimal technical and cost-effective solutions towards the design and implementation of the ICDC Industrial Park in Eldoret. The proposed designs and implementation fall within the Government of Kenya’s Vision 2030 manufacturing sector goals and the need to promote SME parks and industrial clusters.",
    actualServicesProvided: [
      "Master planning",
      "Design documentation",
      "Commercial and industrial development planning",
      "Infrastructure and business-support concept development",
    ],
    consultingFirm: "Kemsal Consultants Ltd",
    signatory: "Qs. Olivia. S. Otieno – Director",
  },
  {
    slug: "kuccps-office-fit-out",
    title: "KUCCPS Office Fit-Out",
    category: "Institutional",
    location: "Nairobi",
    summary: "Interior fit-out and refurbishment works for institutional offices supporting operational efficiency and workplace improvement.",
    description:
      "This project involved design and supervision of a fit-out for Kenya Universities and Colleges Central Placement Service (KUCCPS) offices. The scope focused on upgrading the working environment while keeping quality and cost in control.",
    role: "Quantity surveying and contract administration support for interior fit-out works.",
    services: ["Interior fit-out", "Design and supervision", "Quantity surveying"],
    metrics: [
      { label: "Value", value: "Ksh. 10M" },
      { label: "Duration", value: "4 months" },
      { label: "Staff", value: "2" },
    ],
    folder: "kuccps-office-fit-out",
    heroImage: "/projects/kuccps-office-fit-out/Project-9-Image-1.jpeg",
    projectNumber: "Project No. 9",
    assignmentName: "Design and Supervision of Interior Fit Out",
    contractValue: "Kshs. 10,000,000",
    country: "Kenya",
    duration: "4 months",
    procuringEntity: "Kenya Universities and Colleges Central Placement Service Offices",
    staffMonths: "2 staff",
    address: "P.O. Box 105166 – 00101, Nairobi",
    startDate: "September 2015",
    completionDate: "December 2015",
    associatedConsultants: "University of Nairobi and associated engineering specialists",
    roleOnAssignment: "Design and supervision of interior fit-out",
    seniorProfessionalStaff: ["Qs. Olivia S. Otieno"],
    responsibilities: ["Quantity survey support", "Contract supervision", "Design coordination"],
    narrativeDescription: "Interior office fit-out and refurbishment works to improve functional efficiency in institutional office spaces.",
    actualServicesProvided: ["Design and supervision", "Interior fit-out planning", "Quantity surveying"],
    consultingFirm: "Kemsal Consultants Ltd",
    signatory: "Qs. Olivia. S. Otieno – Director",
  },
  {
    slug: "lesidai-renewable-energy-centre",
    title: "Lesidai Renewable Energy & Business Information Centre",
    category: "Institutional",
    location: "Lesidai, Samburu County",
    summary: "Information and resource centre designed as a climate-sensitive, community-focused facility combining business information services with sustainable energy features.",
    description:
      "The project involved design, documentation, and construction supervision for a community-oriented information and business centre in a remote arid environment. The assignment emphasised sustainability, information accessibility, and an environmentally responsive design approach.",
    role: "Quantity surveying and project supervision support for a rural information centre development.",
    services: ["Design documentation", "Tender documentation", "Construction supervision", "Contract administration"],
    metrics: [
      { label: "Value", value: "Ksh. 40M" },
      { label: "Duration", value: "18 months" },
      { label: "Staff", value: "2" },
    ],
    folder: "lesidai-renewable-energy-centre",
    heroImage: "/projects/lesidai-renewable-energy-centre/Project-10-Image-2.jpeg",
    projectNumber: "Project No. 10",
    assignmentName: "Design, Documentation and Construction Supervision of Proposed Renewable Energy and Business Information Centre in Lesidai, Samburu County",
    contractValue: "Kshs. 40,000,000",
    country: "Kenya",
    duration: "18 months",
    procuringEntity: "Arid Lands Information Network (ALIN) – Sponsored by USAID",
    staffMonths: "2 staff",
    address: "AYMCA Building, State House Crescent off State House Avenue, P.O. Box 10098 - 00100, Nairobi",
    startDate: "May 2017",
    completionDate: "December 2018",
    associatedConsultants: "University of Nairobi, Department of Architecture and Building Science",
    roleOnAssignment: "Design documentation and construction supervision",
    seniorProfessionalStaff: ["Dean, School of Built Environment"],
    responsibilities: [
      "Team leader on this assignment",
      "Quality assurance and control",
      "Project planning and meeting coordination",
      "Design review",
    ],
    narrativeDescription:
      "The centre is designed to provide information access, business support, and cultural retention, while addressing environmental sensitivity and community needs in a remote arid setting. It includes a reception facility, multipurpose hall, demonstration kitchen, youth centre, cultural gallery, management offices, storage facility, M-Pesa shop, ablution block, water storage, and solar lighting provisions.",
    actualServicesProvided: [
      "Preparation of Bills of Quantities",
      "Tender documentation",
      "Construction management",
      "Contract administration",
    ],
    consultingFirm: "Kemsal Consultants Ltd",
    signatory: "Qs. Olivia. S. Otieno – Director",
  },
  {
    slug: "bomet-events-centre",
    title: "Bomet Events Centre",
    category: "Commercial",
    location: "Bomet County",
    summary: "Hotel and events centre design and supervision project focused on delivering a hospitality venue within a strategic county setting.",
    description:
      "KEMSAL supported the design and supervision of a hotel and events centre project, with a focus on delivering a functional hospitality development and supporting the client through design progression and project oversight.",
    role: "Project design and supervision support for a hospitality and events development.",
    services: ["Design supervision", "Project support", "Cost management"],
    metrics: [
      { label: "Value", value: "Ksh. 50M" },
      { label: "Duration", value: "9 months" },
      { label: "Staff", value: "5" },
    ],
    folder: "bomet-events-centre",
    heroImage: "/projects/bomet-events-centre/Project-11-Image-1.jpeg",
    projectNumber: "Project No. 11",
    assignmentName: "Design and supervision of hotel and events centre",
    contractValue: "Kshs. 50,000,000",
    country: "Kenya",
    duration: "9 months",
    procuringEntity: "Amb. Nancy Kirui",
    staffMonths: "5 staff",
    address: "P.O. Box, Bomet",
    startDate: "August 2014",
    completionDate: "December 2015 (Phase 1)",
    associatedConsultants: "N/A",
    roleOnAssignment: "Design and supervision of hotel and events centre",
    seniorProfessionalStaff: ["Qs. Olivia Otieno"],
    responsibilities: ["Project design and supervision", "Administrative support", "Client coordination"],
    narrativeDescription: "The project involved the design and supervision of a hotel and events facility intended to support regional hospitality and event hosting demand.",
    actualServicesProvided: ["Design and supervision", "Project support", "Cost management"],
    consultingFirm: "Kemsal Consultants Ltd",
    signatory: "Qs. Olivia. S. Otieno – Director",
  },
  {
    slug: "epza-commercial-development-athi-river",
    title: "EPZA Commercial Development",
    category: "Commercial",
    location: "Athi-River EPZ, Machakos County",
    summary: "Feasibility study and business case for a PPP commercial development including hotel, retail, entertainment, and office facilities.",
    description:
      "This project involved the preparation of a feasibility study and business case for a major commercial development at the Athi-River EPZ. KEMSAL contributed to financial viability assessment, project concept development, and economic projections for a PPP model.",
    role: "Feasibility modelling and cost support for commercial and residential PPP development concepts.",
    services: ["Feasibility studies", "Financial projections", "Cost estimation", "PPP advisory"],
    metrics: [
      { label: "Project value", value: "KES 7B" },
      { label: "Duration", value: "3 months" },
      { label: "Model period", value: "25 years" },
    ],
    folder: "epza-commercial-development-athi-river",
    heroImage: "/projects/epza-commercial-development-athi-river/Project-12-Image-1.png",
    projectNumber: "Project No. 12",
    assignmentName: "Feasibility Study and Development of a Business Case for The Establishment of a Commercial Development at the Athi-River EPZ, Machakos County",
    contractValue: "KES 7 Billion",
    country: "Kenya",
    duration: "3 months",
    procuringEntity: "Export Processing Zone Authority",
    staffMonths: "2 staff",
    address: "Export Processing Zone Authority, P.O. Box 50563-00200, Nairobi",
    startDate: "October 2016",
    completionDate: "February 2017",
    associatedConsultants: "University of Nairobi and supporting experts",
    roleOnAssignment: "Feasibility study and business case development",
    seniorProfessionalStaff: ["Prof Madara Ogot"],
    responsibilities: [
      "Overall responsibility for the project",
      "Concept development",
      "Market survey support",
      "Financial projections",
    ],
    narrativeDescription:
      "The assignment entailed carrying out a feasibility study for the development of commercial and residential facilities under public-private partnership, including hotels, conference facilities, retail malls, offices, and entertainment blocks on an 11-hectare site.",
    actualServicesProvided: ["Preparation of Detailed Cost Estimates"],
    consultingFirm: "Kemsal Consultants Ltd",
    signatory: "Qs. Olivia. S. Otieno – Director",
  },
  {
    slug: "epza-housing-development-athi-river",
    title: "EPZA Housing Development",
    category: "Affordable Housing",
    location: "Athi-River EPZ, Machakos County",
    summary: "Feasibility and business case development for residential housing within an EPZ setting under PPP framework.",
    description:
      "KEMSAL was engaged in feasibility and business case preparation to evaluate the viability of a residential development at the Athi-River EPZ. The assignment involved reviewing development viability, expected returns, and planning assumptions for a mixed residential development.",
    role: "Feasibility support and detailed financial cost estimation for housing investment planning.",
    services: ["Feasibility studies", "Financial projections", "Cost estimation"],
    metrics: [
      { label: "Project value", value: "KES 21B" },
      { label: "Duration", value: "3 months" },
      { label: "Return metrics", value: "ROI / ROA / IRR" },
    ],
    folder: "epza-housing-development-athi-river",
    heroImage: "/projects/epza-housing-development-athi-river/Project-13-Image-1.png",
    projectNumber: "Project No. 13",
    assignmentName: "Feasibility Study and Development of a Business Case for The Establishment of a Housing Development at the Athi-River EPZ, Machakos County",
    contractValue: "KES 21 Billion",
    country: "Kenya",
    duration: "3 months",
    procuringEntity: "Export Processing Zone Authority (EPZA)",
    staffMonths: "2 staff",
    address: "Export Processing Zone Authority, P.O. Box 50563-00200, Nairobi",
    startDate: "October 2016",
    completionDate: "February 2017",
    associatedConsultants: "University of Nairobi and supporting experts",
    roleOnAssignment: "Feasibility study and business case development",
    seniorProfessionalStaff: ["Prof Madara Ogot"],
    responsibilities: [
      "Overall responsibility for the project",
      "Concept development",
      "Market survey support",
      "Financial projections",
    ],
    narrativeDescription:
      "The assignment involved carrying out feasibility studies for the development of residential properties under a public-private partnership framework, including 2-bedroom and 3-bedroom apartments, maisonettes, and community facilities.",
    actualServicesProvided: ["Preparation of Detailed Cost Estimates"],
    consultingFirm: "Kemsal Consultants Ltd",
    signatory: "Qs. Olivia. S. Otieno – Director",
  },
  {
    slug: "konza-bio-technology-1",
    title: "Konza Bio-Technology 1 Building",
    category: "Institutional",
    location: "Konza Technopolis",
    summary: "Design and documentation of a flagship scientific and innovation building within the Konza Science and Technology Park.",
    description:
      "This project involved design and documentation for a major biotechnology building within Konza Technopolis. KEMSAL supported the project with cost planning and tender documentation, helping define a high-value science infrastructure development aligned to Kenya’s innovation agenda.",
    role: "Quantity surveying and technical documentation support for a science and technology facility.",
    services: ["Bills of quantities", "Tender documentation", "Cost planning"],
    metrics: [
      { label: "Value", value: "Ksh. 4.5B" },
      { label: "Duration", value: "8 months" },
      { label: "Status", value: "Ongoing" },
    ],
    folder: "konza-bio-technology-1",
    heroImage: "/projects/konza-bio-technology-1/Project-14-Image-1.png",
    projectNumber: "Project No. 14",
    assignmentName: "Design and documentation of the Proposed Bio-Technology 1 Building within Konza Science Technology Park",
    contractValue: "Kshs. 4,500,000,000",
    country: "Kenya",
    duration: "8 months",
    procuringEntity: "Ministry of Education, State Department of University Education",
    staffMonths: "2 staff",
    address: "The Ministry of Education, State Department of University Education, P.O. Box 30040-00100, Nairobi",
    startDate: "March 2017",
    completionDate: "Ongoing",
    associatedConsultants: "University of Nairobi and Frost & Sullivan, Singapore",
    roleOnAssignment: "Design and documentation",
    seniorProfessionalStaff: ["Prof Peter Ngau"],
    responsibilities: [
      "Team leader on this assignment",
      "Overall project direction",
      "Quality assurance and control",
      "Planning and presentation support",
    ],
    narrativeDescription:
      "The preparation of Konza STP was a deliberate, systematic and structured action by the Ministry in the quest of transforming Kenya into a knowledge economy. Konza Technology City is a flagship project of Kenya Vision 2030 designed to position Kenya as a leading ICT nation in Africa, with focus on education, life sciences, telecommunications, and ITO/BPO.",
    actualServicesProvided: ["Preparation of Bills of Quantities", "Tender documentation"],
    consultingFirm: "Kemsal Consultants Ltd",
    signatory: "Qs. Olivia. S. Otieno – Director",
  },
  {
    slug: "dedan-kimathi-science-technology-park",
    title: "Dedan Kimathi Science Technology Park",
    category: "Institutional",
    location: "Dedan Kimathi University of Technology, Nyeri",
    summary: "Science and technology park design and documentation aligned to national innovation and academic development goals.",
    description:
      "KEMSAL participated in designing and documenting a science and technology park within the Dedan Kimathi University of Technology environment. The project aimed to establish a practical knowledge-based industrial and innovation anchor supporting Kenya’s technology growth agenda.",
    role: "Quantity surveying and cost documentation support for a science park development.",
    services: ["Bills of quantities", "Tender documentation", "Cost estimation"],
    metrics: [
      { label: "Value", value: "Ksh. 2.5B" },
      { label: "Duration", value: "4 months" },
      { label: "Staff", value: "10" },
    ],
    folder: "dedan-kimathi-science-technology-park",
    heroImage: "/projects/dedan-kimathi-science-technology-park/Project-15-Image-1.png",
    projectNumber: "Project No. 15",
    assignmentName: "Design and documentation of the Proposed Dedan Kimathi Science Technology Park within Dedan Kimathi University of Technology",
    contractValue: "Kshs. 2,500,000,000",
    country: "Kenya",
    duration: "4 months",
    procuringEntity: "Ministry of Education, State Department of University Education",
    staffMonths: "10 staff",
    address: "The Ministry of Education, State Department of University Education, P.O. Box 30040-00100, Nairobi",
    startDate: "March 2017",
    completionDate: "June 2017",
    associatedConsultants: "Frost & Sullivan, Singapore",
    roleOnAssignment: "Design and documentation",
    seniorProfessionalStaff: ["Prof Peter Ngau"],
    responsibilities: [
      "Team leader on this assignment",
      "Overall project direction",
      "Quality assurance and control",
      "Planning and presentation support",
    ],
    narrativeDescription:
      "The proposal forms part of the broader transformation agenda toward building a knowledge economy in Kenya. It is focused on establishing a science and technology hub aligned to education, life sciences, telecommunications, and ITO/BPO innovation sectors.",
    actualServicesProvided: ["Preparation of Bills of Quantities", "Tender documentation"],
    consultingFirm: "Kemsal Consultants Ltd",
    signatory: "Qs. Olivia. S. Otieno – Director",
  },
  {
    slug: "webuye-sda-office-block",
    title: "SDA Northwest Kenya Conference Office Block",
    category: "Institutional",
    location: "Webuye, Bungoma County",
    summary: "Office block design and supervision project delivered for the Seventh Day Adventist Church’s Northwest Kenya Conference headquarters.",
    description:
      "This assignment involved design and construction supervision for a church office block in Webuye. KEMSAL supported the project through quantity surveying, tender documentation, and construction management to assure value for money and delivery quality.",
    role: "Quantity surveying and construction supervision support for church office headquarters works.",
    services: ["Bills of quantities", "Tender documentation", "Construction management", "Contract administration"],
    metrics: [
      { label: "Value", value: "Ksh. 57M" },
      { label: "Duration", value: "6 months" },
      { label: "Staff", value: "3" },
    ],
    folder: "webuye-sda-office-block",
    heroImage: "/projects/webuye-sda-office-block/Project-16-Image-1.jpeg",
    projectNumber: "Project No. 16",
    assignmentName: "Design and Construction Supervision of Office Block for Seventh Day Adventist Church, Northwest Kenya Conference Headquarters in Webuye Town",
    contractValue: "Kshs. 57,000,000",
    country: "Kenya",
    duration: "6 months",
    procuringEntity: "North West Kenya Union Conference, SDA",
    staffMonths: "3 staff",
    address: "P.O. Box 1264, Webuye",
    startDate: "July 2017",
    completionDate: "September 2019",
    associatedConsultants: "OD-SYNC Architecture Ltd",
    roleOnAssignment: "Design and construction supervision",
    seniorProfessionalStaff: ["Qs. Olivia S. Otieno"],
    responsibilities: [
      "Preparation of Bills of Quantities",
      "Tender documentation",
      "Construction management",
      "Contract administration",
    ],
    narrativeDescription: "The project involved the design and construction supervision of an office block for the Seventh Day Adventist Church’s headquarters in Webuye.",
    actualServicesProvided: [
      "Preparation of Bills of Quantities",
      "Tender documentation",
      "Construction management",
      "Contract administration",
    ],
    consultingFirm: "Kemsal Consultants Ltd",
    signatory: "Qs. Olivia. S. Otieno – Director",
  },
  {
    slug: "west-kenya-union-apartments",
    title: "West Kenya Union Apartments",
    category: "Residential",
    location: "Kileleshwa, Nairobi",
    summary: "Apartment development supervision project for West Kenya Union Conference involving residential design management and construction oversight.",
    description:
      "The project focused on the design and construction supervision of apartments off Mazeras Road, Nairobi. The service included project oversight, cost control, and management of construction activities as the design advanced and site works proceeded.",
    role: "Quantity surveying and construction supervision support for apartment delivery works.",
    services: ["Bills of quantities", "Tender documentation", "Construction management", "Contract administration"],
    metrics: [
      { label: "Value", value: "Ksh. 500M" },
      { label: "Duration", value: "12 months" },
      { label: "Staff", value: "3" },
    ],
    folder: "west-kenya-union-apartments",
    heroImage: "/projects/west-kenya-union-apartments/Project-17-Image-1.png",
    projectNumber: "Project No. 17",
    assignmentName: "Design and Construction Supervision of Proposed Apartments off Mazeras road, Nairobi",
    contractValue: "Kshs. 500,000,000",
    country: "Kenya",
    duration: "12 months",
    procuringEntity: "West Kenya Union Conference",
    staffMonths: "3 staff",
    address: "P.O. Box 7747-40100, Kisumu",
    startDate: "January 2019",
    completionDate: "Ongoing",
    associatedConsultants: "Achera and Partners, Nyumba Bora Ltd, Karen",
    roleOnAssignment: "Design and construction supervision",
    seniorProfessionalStaff: ["Qs. Olivia S. Otieno"],
    responsibilities: [
      "Preparation of Bills of Quantities",
      "Tender documentation",
      "Construction management",
      "Contract administration",
    ],
    narrativeDescription: "The project involved design and construction supervision of apartment development works intended to provide residential accommodation for the client organisation.",
    actualServicesProvided: [
      "Preparation of Bills of Quantities",
      "Tender documentation",
      "Construction management",
      "Contract administration",
    ],
    consultingFirm: "Kemsal Consultants Ltd",
    signatory: "Qs. Olivia. S. Otieno – Director",
  },
  {
    slug: "west-kenya-union-staff-housing",
    title: "West Kenya Union Staff Housing",
    category: "Residential",
    location: "Kanyakwar, Kisumu",
    summary: "Staff housing project focused on efficient design, cost control, and site supervision for institutional residential accommodation.",
    description:
      "The project involved the design and construction supervision of residential staff housing for the West Kenya Union Conference. KEMSAL supported the project through technical documentation and on-site project control to achieve value and quality.",
    role: "Quantity surveying and construction supervision during housing implementation.",
    services: ["Bills of quantities", "Tender documentation", "Construction management", "Contract administration"],
    metrics: [
      { label: "Value", value: "Ksh. 300M" },
      { label: "Duration", value: "12 months" },
      { label: "Staff", value: "3" },
    ],
    folder: "west-kenya-union-staff-housing",
    heroImage: "/projects/west-kenya-union-staff-housing/Project-18-Image-1.png",
    projectNumber: "Project No. 18",
    assignmentName: "Design and Construction Supervision of Proposed Staff Housing in Kanyakwar, Kisumu",
    contractValue: "Kshs. 300,000,000",
    country: "Kenya",
    duration: "12 months",
    procuringEntity: "West Kenya Union Conference",
    staffMonths: "3 staff",
    address: "P.O. Box 7747-40100, Kisumu",
    startDate: "January 2015",
    completionDate: "Ongoing",
    associatedConsultants: "Achera and Partners, Nyumba Bora Ltd, Karen",
    roleOnAssignment: "Design and construction supervision",
    seniorProfessionalStaff: ["Qs. Olivia S. Otieno"],
    responsibilities: [
      "Preparation of Bills of Quantities",
      "Tender documentation",
      "Construction management",
      "Contract administration",
    ],
    narrativeDescription: "The project involved the design and construction supervision of proposed staff housing in Kanyakwar, aimed at providing residential units for institutional staff needs.",
    actualServicesProvided: [
      "Preparation of Bills of Quantities",
      "Tender documentation",
      "Construction management",
      "Contract administration",
    ],
    consultingFirm: "Kemsal Consultants Ltd",
    signatory: "Qs. Olivia. S. Otieno – Director",
  },
  {
    slug: "affordable-housing-institute-cost-data",
    title: "Affordable Housing Institute Cost Data Collection",
    category: "Research/Consultancy",
    location: "Nairobi, Kisumu, Mombasa",
    summary: "Cost data collection and benchmarking initiative covering labour and material costs for affordable housing across major Kenyan cities.",
    description:
      "KEMSAL conducted a targeted cost survey for the Affordable Housing Institute covering housing construction inputs in Nairobi, Kisumu, and Mombasa. The work helped inform affordable housing cost assumptions and planning for cost-effective delivery.",
    role: "Cost expert and quantity surveyor supporting housing research and market data collection.",
    services: ["Cost surveys", "Housing cost benchmarking", "Data collection and analysis"],
    metrics: [
      { label: "Duration", value: "3 months" },
      { label: "Cities", value: "3" },
      { label: "Value", value: "Kshs. 10,000 USD" },
    ],
    folder: "epza-business-parks",
    heroImage: "/projects/epza-business-parks/epza-2.svg",
    projectNumber: "Research Project No. 1",
    assignmentName: "Collection of data on costs of labour and materials for typically designed houses",
    contractValue: "Kshs. 10,000 USD",
    country: "Kenya",
    duration: "3 months",
    procuringEntity: "Affordable Housing Institute",
    staffMonths: "6 staff",
    address: "38 Chauncy Street, Suite 600, Boston, MA 02111",
    startDate: "N/A",
    completionDate: "August 2016",
    associatedConsultants: "N/A",
    roleOnAssignment: "Cost expert and Quantity Surveyor",
    seniorProfessionalStaff: ["Qs Olivia Sally Otieno-Mwembe"],
    responsibilities: ["Data collection", "Cost analysis", "Housing benchmark reporting"],
    narrativeDescription: "The project aimed to gather data on labour and material costs for typically designed housing units in order to support affordable housing planning and cost benchmarking.",
    actualServicesProvided: ["Cost surveys", "Data collection", "Cost benchmarking"],
    consultingFirm: "Kemsal Consultants Ltd",
    signatory: "Qs. Olivia. S. Otieno – Director",
  },
  {
    slug: "affordable-housing-institute-design-cost-estimation",
    title: "Affordable Housing Institute Design Cost Estimation",
    category: "Research/Consultancy",
    location: "Across all regions in Kenya",
    summary: "Design, cost estimation, tender documentation, and tender evaluation support for an affordable housing programme.",
    description:
      "This work supported the Affordable Housing Institute in preparing technical and commercial inputs for an affordable housing initiative across Kenya. KEMSAL contributed to project design cost estimation, tender documents, and evaluation support to strengthen procurement readiness.",
    role: "Cost expert and quantity surveyor supporting project design, tendering, and evaluation processes.",
    services: ["Design cost estimation", "Tender documentation", "Tender evaluation", "Affordable housing costing"],
    metrics: [
      { label: "Duration", value: "Ongoing" },
      { label: "Coverage", value: "National" },
      { label: "Scope", value: "Design & costing" },
    ],
    folder: "epza-business-parks",
    heroImage: "/projects/epza-business-parks/epza-2.svg",
    projectNumber: "Research Project No. 2",
    assignmentName: "Design, cost estimation, preparation of tender documentation and tender evaluation for the affordable housing project",
    contractValue: "Kshs. N/A",
    country: "Kenya",
    duration: "Ongoing",
    procuringEntity: "Affordable Housing Institute",
    staffMonths: "6 staff",
    address: "38 Chauncy Street, Suite 600, Boston, MA 02111",
    startDate: "N/A",
    completionDate: "Ongoing",
    associatedConsultants: "N/A",
    roleOnAssignment: "Cost expert and Quantity Surveyor",
    seniorProfessionalStaff: ["Qs Olivia Sally Otieno-Mwembe"],
    responsibilities: ["Cost estimation", "Tender documentation", "Tender evaluation"],
    narrativeDescription: "The project focuses on design, cost estimation, tender preparation, and evaluation for affordable housing across the country, helping improve procurement quality and cost transparency.",
    actualServicesProvided: ["Design cost estimation", "Tender documentation", "Tender evaluation"],
    consultingFirm: "Kemsal Consultants Ltd",
    signatory: "Qs. Olivia. S. Otieno – Director",
  },
];
export function getProjectBySlug(slug: string): ProjectBase | undefined {
  return projects.find((p) => p.slug === slug);
}
